# Generated by Django 2.2.2 on 2019-06-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(verbose_name='Date Start')),
                ('end_date', models.DateField(verbose_name='Date End')),
                ('event_url', models.URLField()),
                ('img_url', models.URLField()),
            ],
        ),
    ]
