# Generated by Django 2.2.2 on 2019-06-20 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmasAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='AZKXNEAA', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Start'),
        ),
    ]
